### ISSUE TITLE
Ambiguous type names in documentation 

### ISSUE THREAD

**Issue by bartlomiej-stefanski** [antonigoles/CPTG#7]
### One fragment of documentation denotes:
```
available values:
- Char
- Number
- Float
- String
```

### Which is conflicting with one of code examples, viz:
```xml
<test>
    <!-- variables can be of different types -->
    <seq times="3">
        <var type="char" range="abc" />
        <var type="char" range="ABC" />
        <var type="char" range="special" />
        <var type="char" range="all" />
        <var type="string" range="all" length="5" />
        <br/>
    </seq>
</test>
```

## Conclusion
Considering that web compiler, local compiler and python implementation of CPTG all expect uppercase type name, it's most likely the example code stated in the documentation that needs changing to fix erroneousness.

**Comment by antonigoles** [comment]
potwierdzam wszystkie testy
